OWNER_ID = 'owner id (owner has all perms)'
BOT_PREFIX = '!'
TOKEN = 'bot token goes here'
GAME_CHANNEL = 'lobby channel id'
DEBUG_CHANNEL = 'debug channel id (for all your errors and debug stuff)'
WEREWOLF_SERVER = 'id of server the bot is running on'
PLAYERS_ROLE_NAME = 'Players'
ADMINS_ROLE_NAME = 'Admins'
WEREWOLF_NOTIFY_ROLE_NAME = 'Werewolf Notify'
ADMINS = ['admin id', 'admin 2 id', 'etc.']
IGNORE_LIST = []
TOKENS_GIVEN = 5
TOKEN_RESET = 10
IGNORE_THRESHOLD = 7
NOTIFY_FILE = 'notify.txt'
BACKUP_INTERVAL = 300
MESSAGE_LANGUAGE = 'en'
LOG_FILE = 'debug.txt'
MIN_LOG_LEVEL = 1
# 0 to log everything, 1 to log only gameplay-related info, 2 to log only warnings
STASIS_FILE = 'stasis.json'
PLAYING_MESSAGE = '{0}info | {0}help | {0}join'.format(BOT_PREFIX)
