MIN_PLAYERS = 4
MAX_PLAYERS = 24

RETRY_RUN_GAME = 3

PLAYER_TIMEOUT = 300
PLAYER_TIMEOUT2 = 60

DEFAULT_DAY_WARNING = 540
DEFAULT_DAY_TIMEOUT = 600
DEFAULT_NIGHT_WARNING = 90
DEFAULT_NIGHT_TIMEOUT = 120

EXTRA_WAIT = 30
WAIT_AFTER_JOIN = 15
WAIT_BUCKET_INIT = 1
WAIT_BUCKET_DELAY = 240
WAIT_BUCKET_MAX = 3

GAME_START_TIMEOUT = 60 * 30 # 30 minutes
QUIT_GAME_STASIS = 2

GUNNER_MISS = 1
GUNNER_SUICIDE = 1
GUNNER_HEADSHOT = 2
GUNNER_INJURE = 3
DRUNK_MISS = 3
DRUNK_SUICIDE = 2
DRUNK_HEADSHOT = 2
DRUNK_INJURE = 2
GUNNER_MULTIPLIER = 0.12 # bullets = ceil(num players * multiplier)
SHARPSHOOTER_MULTIPLIER = 0.06
DRUNK_MULTIPLIER = 3
GUNNER_REVENGE_WOLF = 0.25 # chance that gunner will kill wolf

DETECTIVE_REVEAL_CHANCE = 0.4
