MIN_PLAYERS = 4
MAX_PLAYERS = 20

RETRY_RUN_GAME = 3

PLAYER_TIMEOUT = 300
PLAYER_TIMEOUT2 = 60

DAY_WARNING = 540
DAY_TIMEOUT = 600
NIGHT_WARNING = 90
NIGHT_TIMEOUT = 120

EXTRA_WAIT = 30
WAIT_AFTER_JOIN = 25
WAIT_BUCKET_INIT = 2
WAIT_BUCKET_DELAY = 240
WAIT_BUCKET_MAX = 3

GAME_START_TIMEOUT = 60 * 30 # 30 minutes
QUIT_GAME_STASIS = 2

GUNNER_MISS = 1
GUNNER_SUICIDE = 1
GUNNER_HEADSHOT = 2
GUNNER_INJURE = 3
GUNNER_MULTIPLIER = 0.12 # bullets = ceil(num players * multiplier)
GUNNER_REVENGE_WOLF = 0.25 # chance that gunner will kill wolf

DETECTIVE_REVEAL_CHANCE = 0.4
